// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEee_EzTBc-r-OMNDmFJsicLEVop4IKI4',
    appId: '1:1081833423538:web:e0a532c53917ba1761bfab',
    messagingSenderId: '1081833423538',
    projectId: 'loyaltywallet-111600',
    authDomain: 'loyaltywallet-111600.firebaseapp.com',
    storageBucket: 'loyaltywallet-111600.appspot.com',
    measurementId: 'G-K7DKN1WZQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4yyd-CmjnCZ6BXIi93YS6TIQ5f6t9Emc',
    appId: '1:1081833423538:android:aa01f08ea218363761bfab',
    messagingSenderId: '1081833423538',
    projectId: 'loyaltywallet-111600',
    storageBucket: 'loyaltywallet-111600.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCD8_laQdc80hty3ryNKU6U6wUGAFyR_0',
    appId: '1:1081833423538:ios:87fbfe8b915b176061bfab',
    messagingSenderId: '1081833423538',
    projectId: 'loyaltywallet-111600',
    storageBucket: 'loyaltywallet-111600.appspot.com',
    iosBundleId: 'com.example.loyaltywallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCD8_laQdc80hty3ryNKU6U6wUGAFyR_0',
    appId: '1:1081833423538:ios:fe262f84d03f741061bfab',
    messagingSenderId: '1081833423538',
    projectId: 'loyaltywallet-111600',
    storageBucket: 'loyaltywallet-111600.appspot.com',
    iosBundleId: 'com.example.loyaltywallet.RunnerTests',
  );
}
